const states = [
    {
        label: "Initial State",
        desc: "Vectors <strong>x</strong>=[x₀,x₁,x₂,x₃] and <strong>y</strong>=[y₀,y₁,y₂,y₃] loaded onto the LRU stack.<br>y₃ is most-recently-used (depth 1). x₀ is deepest (depth 8, ring 3).",
        vars: { x0: 8, x1: 7, x2: 6, x3: 5, y0: 4, y1: 3, y2: 2, y3: 1 },
        reads: [],
        cost: 0, delta: 0,
    },
    {
        label: "Step 1A — Highlight x₀, y₀",
        desc: "Identify x₀ at depth 8 (cost = ⌈√8⌉ = <strong>3</strong>) and y₀ at depth 4 (cost = ⌈√4⌉ = <strong>2</strong>).<br>Cost paths shown in red.",
        vars: { x0: 8, x1: 7, x2: 6, x3: 5, y0: 4, y1: 3, y2: 2, y3: 1 },
        reads: [{ id: 'x0', depth: 8 }, { id: 'y0', depth: 4 }],
        cost: 5, delta: 5,
    },
    {
        label: "Step 1B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x0: 'proc', x1: 6, x2: 5, x3: 4, y0: 'proc', y1: 3, y2: 2, y3: 1 },
        reads: [{ id: 'x0', depth: 8 }, { id: 'y0', depth: 4 }],
        cost: 5, delta: 0,
    },
    {
        label: "Step 1C — Store m₀ = x₀·y₀",
        desc: "Product <strong>m₀</strong> pushed to depth 1. All survivors pushed outward by 1.",
        vars: { x1: 7, x2: 6, x3: 5, y1: 4, y2: 3, y3: 2, m0: 1 },
        reads: [],
        cost: 5, delta: 0,
    },
    {
        label: "Step 2A — Highlight x₁, y₁",
        desc: "Identify x₁ at depth 7 (cost = ⌈√7⌉ = <strong>3</strong>) and y₁ at depth 4 (cost = ⌈√4⌉ = <strong>2</strong>).<br>Cost paths shown in red.",
        vars: { x1: 7, x2: 6, x3: 5, y1: 4, y2: 3, y3: 2, m0: 1 },
        reads: [{ id: 'x1', depth: 7 }, { id: 'y1', depth: 4 }],
        cost: 10, delta: 5,
    },
    {
        label: "Step 2B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x1: 'proc', x2: 5, x3: 4, y1: 'proc', y2: 3, y3: 2, m0: 1 },
        reads: [{ id: 'x1', depth: 7 }, { id: 'y1', depth: 4 }],
        cost: 10, delta: 0,
    },
    {
        label: "Step 2C — Store m₁ = x₁·y₁",
        desc: "Product <strong>m₁</strong> pushed to depth 1. Survivors pushed outward.",
        vars: { x2: 6, x3: 5, y2: 4, y3: 3, m0: 2, m1: 1 },
        reads: [],
        cost: 10, delta: 0,
    },
    {
        label: "Step 3A — Highlight m₀, m₁",
        desc: "Identify m₀ at depth 2 (cost = ⌈√2⌉ = <strong>2</strong>) and m₁ at depth 1 (cost = ⌈√1⌉ = <strong>1</strong>).<br>Cost paths shown in red.",
        vars: { x2: 6, x3: 5, y2: 4, y3: 3, m0: 2, m1: 1 },
        reads: [{ id: 'm0', depth: 2 }, { id: 'm1', depth: 1 }],
        cost: 13, delta: 3,
    },
    {
        label: "Step 3B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x2: 4, x3: 3, y2: 2, y3: 1, m0: 'proc', m1: 'proc' },
        reads: [{ id: 'm0', depth: 2 }, { id: 'm1', depth: 1 }],
        cost: 13, delta: 0,
    },
    {
        label: "Step 3C — Store s₀₁ = m₀ + m₁",
        desc: "Partial sum <strong>s₀₁</strong> = x₀y₀ + x₁y₁ pushed to depth 1. Survivors pushed outward.",
        vars: { x2: 5, x3: 4, y2: 3, y3: 2, s01: 1 },
        reads: [],
        cost: 13, delta: 0,
    },
    {
        label: "Step 4A — Highlight x₂, y₂",
        desc: "Identify x₂ at depth 5 (cost = ⌈√5⌉ = <strong>3</strong>) and y₂ at depth 3 (cost = ⌈√3⌉ = <strong>2</strong>).<br>Cost paths shown in red.",
        vars: { x2: 5, x3: 4, y2: 3, y3: 2, s01: 1 },
        reads: [{ id: 'x2', depth: 5 }, { id: 'y2', depth: 3 }],
        cost: 18, delta: 5,
    },
    {
        label: "Step 4B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x2: 'proc', x3: 3, y2: 'proc', y3: 2, s01: 1 },
        reads: [{ id: 'x2', depth: 5 }, { id: 'y2', depth: 3 }],
        cost: 18, delta: 0,
    },
    {
        label: "Step 4C — Store m₂ = x₂·y₂",
        desc: "Product <strong>m₂</strong> pushed to depth 1. Survivors pushed outward.",
        vars: { x3: 4, y3: 3, s01: 2, m2: 1 },
        reads: [],
        cost: 18, delta: 0,
    },
    {
        label: "Step 5A — Highlight s₀₁, m₂",
        desc: "Identify s₀₁ at depth 2 (cost = ⌈√2⌉ = <strong>2</strong>) and m₂ at depth 1 (cost = ⌈√1⌉ = <strong>1</strong>).<br>Cost paths shown in red.",
        vars: { x3: 4, y3: 3, s01: 2, m2: 1 },
        reads: [{ id: 's01', depth: 2 }, { id: 'm2', depth: 1 }],
        cost: 21, delta: 3,
    },
    {
        label: "Step 5B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x3: 2, y3: 1, s01: 'proc', m2: 'proc' },
        reads: [{ id: 's01', depth: 2 }, { id: 'm2', depth: 1 }],
        cost: 21, delta: 0,
    },
    {
        label: "Step 5C — Store s₀₁₂ = s₀₁ + m₂",
        desc: "Partial sum <strong>s₀₁₂</strong> = x₀y₀ + x₁y₁ + x₂y₂ pushed to depth 1. Survivors pushed outward.",
        vars: { x3: 3, y3: 2, s012: 1 },
        reads: [],
        cost: 21, delta: 0,
    },
    {
        label: "Step 6A — Highlight x₃, y₃",
        desc: "Identify x₃ at depth 3 (cost = ⌈√3⌉ = <strong>2</strong>) and y₃ at depth 2 (cost = ⌈√2⌉ = <strong>2</strong>).<br>Cost paths shown in red.",
        vars: { x3: 3, y3: 2, s012: 1 },
        reads: [{ id: 'x3', depth: 3 }, { id: 'y3', depth: 2 }],
        cost: 25, delta: 4,
    },
    {
        label: "Step 6B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { x3: 'proc', y3: 'proc', s012: 1 },
        reads: [{ id: 'x3', depth: 3 }, { id: 'y3', depth: 2 }],
        cost: 25, delta: 0,
    },
    {
        label: "Step 6C — Store m₃ = x₃·y₃",
        desc: "Product <strong>m₃</strong> pushed to depth 1. s₀₁₂ pushed to depth 2.",
        vars: { s012: 2, m3: 1 },
        reads: [],
        cost: 25, delta: 0,
    },
    {
        label: "Step 7A — Highlight s₀₁₂, m₃",
        desc: "Identify s₀₁₂ at depth 2 (cost = ⌈√2⌉ = <strong>2</strong>) and m₃ at depth 1 (cost = ⌈√1⌉ = <strong>1</strong>).<br>Cost paths shown in red.",
        vars: { s012: 2, m3: 1 },
        reads: [{ id: 's012', depth: 2 }, { id: 'm3', depth: 1 }],
        cost: 28, delta: 3,
    },
    {
        label: "Step 7B — Pull into PE",
        desc: "Variables pulled into processor.<br>Dead variables <em>vaporized</em>. Survivors slide.",
        vars: { s012: 'proc', m3: 'proc' },
        reads: [{ id: 's012', depth: 2 }, { id: 'm3', depth: 1 }],
        cost: 28, delta: 0,
    },
    {
        label: "Final — Store z = x₀y₀ + x₁y₁ + x₂y₂ + x₃y₃",
        desc: "Dot product result <strong>z</strong> stored at depth 1.<br>Total ByteDMD cost = <strong>28</strong> — the sum of Manhattan distances over all reads.",
        vars: { z: 1 },
        reads: [],
        cost: 28, delta: 0,
    },
];